name: Deploy Lambda Function
on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: MyNewLambdaFunction
  AWS_ROLE_TO_ASSUME1: arn:aws:iam::127489365181:role/gitactions-lambda-role

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install awscli pytest

    - name: Run unit tests
      run: |
        python -m unittest discover -s . -p 'test_*.py'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gitactions-lambda-role
        role-session-name: GitHubActionsLambdaDeployment

    - name: Zip the Lambda function
      run: zip function.zip lambda_function.py

    - name: Check if Lambda function exists
      id: check_lambda
      run: |
        if aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }}; then
          echo "::set-output name=lambda_exists::true"
        else
          echo "::set-output name=lambda_exists::false"
        fi

    - name: Create or Update Lambda function
      run: |
        if [ "${{ steps.check_lambda.outputs.lambda_exists }}" == "false" ]; then
          echo "Creating Lambda function..."
          aws lambda create-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --runtime python3.8 --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gitactions-lambda-role \
            --handler lambda_function.lambda_handler --zip-file fileb://function.zip
        else
          echo "Updating Lambda function..."
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://function.zip --publish
        fi

    - name: Add lambda url
      run: |    
        echo "Enabling a URL for the Lambda function..."
            aws lambda create-function-url-config \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --auth-type NONE
    - name: Add permission to lambda function
      run: |    
        echo "Adding permission to lambda function"
            aws lambda add-permission --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --statement-id example1-permission \
            --action lambda:InvokeFunctionUrl \
            --principal "*" \
            --function-url-auth-type NONE
    - name: Clean up
      run: rm function.zip